'use strict';
const {need}=require('./common.cjs');
const {validateBase}=require('./base-diagnostics.cjs');
const stages=['input','uid','module','initialize-state','initialize-window','initialize-owner','construct','retired-admission','open','snapshot','drained','action'];
const stateCodes=['EACCES','EPERM','ENOENT','ENOTDIR','EISDIR','EEXIST','ELOOP','EIO','ENOSPC','EMFILE','ENFILE','MODULE_NOT_FOUND','ERR_MODULE_NOT_FOUND','ERR_REQUIRE_ESM','state_owner_required','binding_missing','private_directory_required','state_file_invalid','state_binding_invalid','generation_retired','admission_closed','unsupported_state_operation','invalid_input','other'];
const codes=['unclassified','truncated','aggregate','command_failed','command_timeout','output_limit','spawn_failed','process_completion_unverified','evidence_write_failed','state_operation_failed','state_diagnostic_missing','state_diagnostic_invalid','cleanup_identity_unverified','cleanup_preexisting_forbidden','cleanup_ownership','container_completion_unverified','never_started_on_success','infrastructure_shutdown_failed','postgres_clean_shutdown_missing','closure_incomplete','overall_deadline','deadline','deadline_binding','primary_and_closure_failed','primary_and_record_failed','closure_and_record_failed'];
const signals=['SIGTERM','SIGKILL','SIGINT','SIGABRT','SIGSEGV'];
const roles=['postgres','redis','probe','restore-postgres','api','admin-writer','dashboard','reporter','widget'];
const states=['never_started','exited','exited_unclean','graceful','unverified'];
const own=(v,keys)=>v&&typeof v==='object'&&!Array.isArray(v)&&JSON.stringify(Object.keys(v).sort())===JSON.stringify([...keys].sort());
function stateDiagnostic(error,stage){return{version:1,stage:stages.includes(stage)?stage:'action',code:stateCodes.includes(error?.code)?error.code:'other'};}
function validateState(v){need(own(v,['version','stage','code'])&&v.version===1&&stages.includes(v.stage)&&stateCodes.includes(v.code),'state_diagnostic_invalid');return v;}
function decodeState(stderr){const s=stderr.toString();need(s.length<=1024&&s.startsWith('SSB_STATE_DIAGNOSTIC_V1 '),'state_diagnostic_missing');let v;try{v=JSON.parse(s.slice(24));}catch{need(false,'state_diagnostic_invalid');}validateState(v);need(s==='SSB_STATE_DIAGNOSTIC_V1 '+JSON.stringify(v)+'\n','state_diagnostic_invalid');return v;}
function publicFailure(error){let count=0;const visit=(e,depth)=>{if(++count>16||depth>4)return{code:'truncated',process:null,state:null,causes:[]};const code=codes.includes(e?.code)?e.code:e instanceof AggregateError?'aggregate':'unclassified';let process=null,state=null;if(e?.process){const p=e.process;process={index:Number.isInteger(p.index)&&p.index>=0&&p.index<=10000?p.index:null,exit:Number.isInteger(p.code)&&p.code>=-4096&&p.code<=255?p.code:null,signal:signals.includes(p.signal)?p.signal:null,closed:p.closed===true,timeout:p.timeout===true};}if(e?.stateDiagnostic){try{state=validateState(e.stateDiagnostic);}catch{}}
 const causes=[];for(const child of (Array.isArray(e?.errors)?e.errors.slice(0,4):e?.cause?[e.cause]:[])){if(count>=16){causes.push({code:'truncated',process:null,state:null,causes:[]});break;}causes.push(visit(child,depth+1));}const result={code,process,state,causes};if(e?.baseDiagnostic&&code==='command_failed'&&process?.closed&&process.exit!==null&&process.exit!==0&&!process.timeout&&!process.signal&&state===null){try{const b=validateBase(e.baseDiagnostic);result.base={reference:b.reference,category:b.category,httpStatus:b.httpStatus};}catch{}}return result;};return visit(error,0);}
function validateFailure(v,depth=0,counter={n:0}){need(++counter.n<=32&&depth<=5&&own(v,['code','process','state','causes',...(v&&Object.hasOwn(v,'base')?['base']:[])])&&codes.includes(v.code)&&Array.isArray(v.causes)&&v.causes.length<=4,'public_diagnostic_invalid');if(v.process!==null){const p=v.process;need(own(p,['index','exit','signal','closed','timeout'])&&(p.index===null||Number.isInteger(p.index)&&p.index>=0&&p.index<=10000)&&(p.exit===null||Number.isInteger(p.exit)&&p.exit>=-4096&&p.exit<=255)&&(p.signal===null||signals.includes(p.signal))&&typeof p.closed==='boolean'&&typeof p.timeout==='boolean','public_process_invalid');}if(v.state!==null)validateState(v.state);if(Object.hasOwn(v,'base')){validateBase(v.base);need(v.code==='command_failed'&&v.process?.closed&&v.process.exit!==null&&v.process.exit!==0&&!v.process.timeout&&!v.process.signal&&v.state===null,'base_process_invalid');}for(const c of v.causes)validateFailure(c,depth+1,counter);}
function validateDetail(r){const d=r.detail;need(own(d,['failure','outcomes'])&&Array.isArray(d.outcomes)&&d.outcomes.length<=19,'receipt_detail_invalid');if(d.failure!==null)validateFailure(d.failure);need(r.ok?d.failure===null:d.failure!==null,'receipt_failure_required');if(r.phase!=='closure')need(d.outcomes.length===0,'unexpected_outcomes');for(const o of d.outcomes){need(own(o,['id','role','generation','state','exit','code'])&&(o.id===null||/^[a-f0-9]{64}$/.test(o.id))&&roles.includes(o.role)&&['seed','release','forward','normal'].includes(o.generation)&&states.includes(o.state)&&(o.exit===null||Number.isInteger(o.exit)&&o.exit>=0&&o.exit<=255)&&['none','forced_or_nonzero',...codes].includes(o.code),'closure_outcome_invalid');if(o.state==='never_started')need(o.id!==null&&o.exit===null&&o.code==='none','never_started_invalid');if(o.state==='graceful'||o.state==='exited')need(o.id!==null&&o.exit===0&&o.code==='none','clean_exit_invalid');if(o.state==='exited_unclean')need(o.id!==null&&Number.isInteger(o.exit)&&o.exit>0&&o.code==='forced_or_nonzero','unclean_exit_invalid');if(o.state==='unverified')need(o.code!=='none','unverified_code_required');}
 const checkBasePhase=v=>{if(!v)return;if(Object.hasOwn(v,'base'))need(r.phase==='bases'&&!r.ok,'base_phase_invalid');for(const c of v.causes)checkBasePhase(c);};checkBasePhase(d.failure);
 if(r.phase==='closure'){if(!r.ok&&r.counts.length===0){need(r.ids.length===0&&d.outcomes.length===0,'unknown_closure_scope');return;}const count=r.counts[0];need(Number.isInteger(count)&&d.outcomes.length===count,'closure_outcomes_missing');need(new Set(d.outcomes.filter(x=>x.id).map(x=>x.id)).size===d.outcomes.filter(x=>x.id).length,'closure_outcome_duplicate');need(JSON.stringify(d.outcomes.filter(x=>x.id).map(x=>x.id))===JSON.stringify(r.ids.slice(0,r.counts[1]||0)),'closure_outcome_binding');if(r.ok)need(d.outcomes.every(o=>o.state!=='unverified'),'closure_outcome_unverified');}}
module.exports={stateDiagnostic,validateState,decodeState,publicFailure,validateFailure,validateDetail,stages,stateCodes,codes};
