'use strict';
// Offline only: Docker is simulated. UID 1000 and its DAC checks are explicitly modeled.
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os'),vm=require('node:vm'),{EventEmitter}=require('node:events'),{spawnSync}=require('node:child_process'),{stripTypeScriptTypes}=require('node:module');
const {Native}=require('./native.cjs'),{main,SOURCE}=require('./controller.cjs'),{sha}=require('./common.cjs');
const {publicFailure,decodeState,validateDetail,validateFailure}=require('./diagnostics.cjs'),{Receipts,parseReceipts}=require('./evidence.cjs');
const historical=path.resolve(__dirname,'../../../../ssb-native-forward-recovery-reviewed-20261009.9wgIuS/publication/.github/ssb-native-forward-recovery');
const source=path.resolve(__dirname,'../../../../ssb-native-e1-recovery-preparation-20261009.j8EmJx/release-source/apps/api/src/maintenance/maintenance-state.ts');
const options={authorization:'ONE_NATIVE_FORWARD_RECOVERY',run:'12345678',attempt:'1',workflowHead:'a'.repeat(40),dispatchNonce:'b'.repeat(64)};
function container(){return{Id:'c'.repeat(64),Name:'/own',Image:'sha256:'+'d'.repeat(64),Config:{Labels:{'com.ssb.native-run':options.run}},RestartCount:0,State:{Status:'created',Running:false,Paused:false,Restarting:false,Dead:false,OOMKilled:false,Error:'',Pid:0,ExitCode:0,StartedAt:'0001-01-01T00:00:00Z',FinishedAt:'0001-01-01T00:00:00Z'}};}
function closure({Ctor=Native,mutate=()=>{},entry={},start=false,exit=0,finalMutate=()=>{},failure=null}={}){const n=new Ctor(options),x=container(),calls=[];mutate(x);if(start)Object.assign(x.State,{Status:'running',Running:true,Pid:123,StartedAt:'2026-10-09T20:00:00Z'});n.initial={containers:[]};n.proc={calls:[],assertClosed(){}};n.owned=[{id:x.Id,name:'own',image:x.Image,role:'probe',startRequested:start,...entry}];let inspections=0;n.d=async(args)=>{calls.push(args);n.proc.calls.push({closed:true});if(failure)throw failure;if(args[0]==='stop'){Object.assign(x.State,{Status:'exited',Running:false,Pid:0,ExitCode:exit,FinishedAt:'2026-10-09T20:01:00Z'});return{stdout:Buffer.from(x.Id)};}assert.deepEqual(args.slice(0,2),['container','inspect']);if(++inspections>1)finalMutate(x);return{stdout:Buffer.from(JSON.stringify([x]))};};return{n,calls,x};}
test('historical actual close rejects owned never-started container, corrected close classifies it without stop',async()=>{const Before=require(path.join(historical,'native.cjs')).Native,old=closure({Ctor:Before});await assert.rejects(old.n.close(true),e=>e.errors.some(x=>x.code==='container_completion_unverified'));const h=closure(),r=await h.n.close(true);assert.equal(r.verified,true);assert.equal(r.detail.outcomes[0].state,'never_started');assert.equal(r.detail.outcomes[0].exit,null);assert.equal(h.calls.length,2);assert.ok(h.calls.every(x=>x[0]!=='stop'));});
for(const [name,mutate,entry]of [
 ['nonzero start',x=>x.State.StartedAt='2026-10-09T20:00:00Z',{}],['missing start',x=>delete x.State.StartedAt,{}],['nonzero end',x=>x.State.FinishedAt='2026-10-09T20:00:00Z',{}],['restart',x=>x.RestartCount=1,{}],['missing restart',x=>delete x.RestartCount,{}],['paused',x=>x.State.Paused=true,{}],['dead',x=>x.State.Dead=true,{}],['error',x=>x.State.Error='SYNTHETIC_PRIVATE',{}],['exit',x=>x.State.ExitCode=137,{}],['pid',x=>x.State.Pid=3,{}],['start attempted',()=>{},{startRequested:true}],['start unknown',()=>{},{startRequested:undefined}],
])test('created rejects ambiguous history: '+name,async()=>{const h=closure({mutate,entry});await assert.rejects(h.n.close(true));assert.ok(h.calls.every(x=>x[0]!=='stop'));});
test('never started is not successful whole-run shutdown',async()=>{await assert.rejects(closure().n.close(false),e=>e.errors.some(x=>x.code==='never_started_on_success'));});
for(const field of ['Id','Name','Image','Labels'])test('both final identity and ownership are rechecked: '+field,async()=>{const h=closure({finalMutate:x=>field==='Labels'?x.Config.Labels={}:x[field]='changed'});await assert.rejects(h.n.close(true));});
test('preexisting identity cannot be adopted or stopped',async()=>{const h=closure({start:true});h.n.initial.containers=[h.x.Id];await assert.rejects(h.n.close(true));assert.equal(h.calls.length,1);});
test('SIGKILL-style 137 means terminated unclean, not graceful',async()=>{const h=closure({start:true,exit:137}),r=await h.n.close(true);assert.equal(r.detail.outcomes[0].state,'exited_unclean');assert.equal(r.detail.outcomes[0].exit,137);await assert.rejects(closure({start:true,exit:137}).n.close(false));});
test('zero exit alone is exited, verified application shutdown is separate',async()=>{let r=await closure({start:true}).n.close(true);assert.equal(r.detail.outcomes[0].state,'exited');r=await closure({start:true,entry:{role:'api',orderedShutdown:true}}).n.close(true);assert.equal(r.detail.outcomes[0].state,'graceful');});
test('timeout stays failed and exported with bounded process fields',async()=>{const e=Object.assign(Error('SYNTHETIC_PRIVATE'),{code:'command_timeout',process:{index:4,code:137,signal:'SIGKILL',closed:false,timeout:true,argv:['SECRET']}}),h=closure({failure:e});await assert.rejects(h.n.close(true),x=>{const d=publicFailure(x);assert.equal(d.causes[0].process.timeout,true);assert.doesNotMatch(JSON.stringify(d),/SYNTHETIC_PRIVATE|SECRET|argv/);return true;});});

async function helper({before=false,uid=1000,fault=null,payload,action='initialize',stateOwner=1000,stateMode=0o700,ancestorMode=0o711,toolsMode=0o755,importsOnly=false}={}){
 const tmp=fs.mkdtempSync(path.join(os.tmpdir(),'ssb-state-offline-')),root=path.join(tmp,'state');fs.mkdirSync(root,{mode:0o700});
 const fsModel={...fs,lstatSync(p){const s=fs.lstatSync(p);Object.defineProperty(s,'uid',{value:1000});return s;},fstatSync(fd){const s=fs.fstatSync(fd);Object.defineProperty(s,'uid',{value:1000});return s;}};
 const access=(owner,mode,required)=>{const bits=uid===owner?(mode>>6)&7:mode&7;if((bits&required)!==required)throw Object.assign(Error('SYNTHETIC_PRIVATE_DAC_PATH'),{code:'EACCES'});};
 for(const op of ['writeFileSync','mkdirSync'])fsModel[op]=(...args)=>{const p=String(args[0]);access(0,ancestorMode,1);access(stateOwner,stateMode,3);if(fault?.operation===op&&p.endsWith(fault.suffix))throw Object.assign(Error('SYNTHETIC_PRIVATE_PATH_AND_CONTENT'),{code:fault.code});return fs[op](...args);};
 // The bound TypeScript class executes unchanged after type erasure in the offline VM.
 const context=vm.createContext({process:{getuid:()=>uid},Buffer,performance,SharedArrayBuffer,Atomics,Int32Array,structuredClone});
 const module=new vm.SourceTextModule(stripTypeScriptTypes(fs.readFileSync(source,'utf8'),{mode:'transform'}),{context});
 await module.link(id=>{const values=id==='node:fs'?fsModel:require(id);return new vm.SyntheticModule(Object.keys(values),function(){for(const k of Object.keys(values))this.setExport(k,values[k]);},{context});});await module.evaluate();
 const file=path.join(before?historical:__dirname,'state-agent.cjs'),m={exports:{}},stdin=new EventEmitter(),stdout=[],stderr=[];
 const proc={getuid:()=>uid,stdin,stdout:{write:x=>stdout.push(x)},stderr:{write:x=>stderr.push(x)}};
 const req=id=>{if(id==='node:fs')return fsModel;if(id.endsWith('/maintenance-state.js')){access(0,ancestorMode,1);access(0,toolsMode,5);if(fault?.operation==='module')throw Object.assign(Error('SYNTHETIC_PRIVATE_MODULE_PATH'),{code:fault.code});return{MaintenanceState:module.namespace.MaintenanceState};}return require(id);};req.main=importsOnly?{}:m;
 vm.runInNewContext(fs.readFileSync(file,'utf8'),{require:req,module:m,exports:m.exports,process:proc,Buffer,__dirname:path.dirname(file)},{filename:file});
 const input={action,toolsRoot:'/synthetic-tools',binding:{root,service:'synthetic',generation:'seed'},owner:'synthetic-private-owner'};
 if(!importsOnly){stdin.emit('data',Buffer.from(payload===undefined?JSON.stringify(input):payload));stdin.emit('end');await new Promise(r=>setImmediate(r));}
 return{root,tmp,input,proc,stdout:stdout.join(''),stderr:stderr.join(''),run:m.exports.run};
}
test('actual stdin entry initializes exactly once; synthetic UID1000, real files and real state implementation',async()=>{const h=await helper();assert.equal(h.proc.exitCode,undefined);assert.deepEqual(JSON.parse(h.stdout),{epoch:0,syntheticNewService:true});assert.equal(h.stderr,'');const s=JSON.parse(fs.readFileSync(path.join(h.root,'runtime-state.json')));assert.equal(s.phase,'closed');assert.deepEqual(s.work,{});assert.equal(fs.statSync(path.join(h.root,'runtime-state.json')).mode&511,384);assert.equal(fs.statSync(path.join(h.root,'maintenance-window')).mode&511,448);assert.equal((await h.run({...h.input,action:'snapshot'})).phase,'closed');await assert.rejects(h.run(h.input),e=>e.code==='EEXIST');});
test('historical helper loses actual EACCES stage; new helper preserves only bounded code',async()=>{const fault={operation:'writeFileSync',suffix:'runtime-state.json',code:'EACCES'},old=await helper({before:true,fault}),next=await helper({fault});assert.equal(old.stderr,'state-operation-failed\n');assert.equal(old.proc.exitCode,1);assert.equal(next.proc.exitCode,1);assert.deepEqual(decodeState(next.stderr),{version:1,stage:'initialize-state',code:'EACCES'});assert.equal(next.stdout,'');assert.doesNotMatch(next.stderr,/PRIVATE|owner|PATH|CONTENT/);});
for(const [stage,fault]of [['module',{operation:'module',code:'MODULE_NOT_FOUND'}],['module',{operation:'module',code:'EACCES'}],['initialize-window',{operation:'mkdirSync',suffix:'maintenance-window',code:'EACCES'}],['initialize-owner',{operation:'writeFileSync',suffix:'owner.json',code:'ENOSPC'}]])test('actual helper stdin diagnoses '+stage+' '+fault.code,async()=>{const h=await helper({fault});assert.equal(h.proc.exitCode,1);assert.equal(decodeState(h.stderr).stage,stage);assert.equal(decodeState(h.stderr).code,fault.code);assert.equal(h.stdout,'');});
test('wrong UID and malformed stdin fail; no initialization',async()=>{for(const config of [{uid:501},{payload:'{'},{payload:'x'.repeat(65537)}]){const h=await helper(config);assert.equal(h.proc.exitCode,1);assert.equal(h.stdout,'');assert.ok(!fs.existsSync(path.join(h.root,'runtime-state.json')));assert.doesNotThrow(()=>decodeState(h.stderr));}});
test('real local process cannot impersonate UID1000; no sudo or account change',()=>{assert.notEqual(process.getuid(),1000);const r=spawnSync(process.execPath,[path.join(__dirname,'state-agent.cjs')],{input:'{}',encoding:'utf8',timeout:1500});assert.equal(r.status,1);assert.equal(decodeState(r.stderr).code,'state_owner_required');});
test('Native.state actual invocation retains stdin UID/GID timeout and sanitized failure cause',async()=>{const n=new Native(options);n.toolsRoot='/synthetic-tools';n.synthetic={owner:'SYNTHETIC_PRIVATE_OWNER'};n.proc={calls:[{index:1,code:1,closed:true,timeout:false}]};let seen;n.command=async(bin,args,o)=>{seen={bin,args,o};throw Object.assign(Error('PRIVATE'),{code:'command_failed',stateDiagnostic:{version:1,stage:'module',code:'EACCES'}});};await assert.rejects(n.state('initialize',{root:'/synthetic-state',service:'synthetic',generation:'seed'}),e=>{const d=publicFailure(e);assert.equal(d.code,'command_failed');assert.equal(d.state.code,'EACCES');assert.doesNotMatch(JSON.stringify(d),/OWNER|synthetic/);return true;});assert.equal(seen.o.stateDiagnostic,true);assert.notEqual(seen.o.allowFailure,true);assert.equal(seen.o.uid,1000);assert.equal(seen.o.gid,1000);assert.equal(seen.o.ms,1000);assert.equal(JSON.parse(seen.o.input).action,'initialize');});
test('bounded diagnostic rejects arbitrary codes, paths, extra keys and malformed outputs',()=>{for(const s of ['','state-operation-failed\n','SSB_STATE_DIAGNOSTIC_V1 {','SSB_STATE_DIAGNOSTIC_V1 {"version":1,"stage":"/private/path","code":"EACCES"}\n','SSB_STATE_DIAGNOSTIC_V1 {"version":1,"stage":"module","code":"SECRET"}\n','SSB_STATE_DIAGNOSTIC_V1 {"version":1,"stage":"module","code":"EACCES","secret":"private"}\n'])assert.throws(()=>decodeState(s));const e=Object.assign(Error('PRIVATE'),{code:'SECRET',stateDiagnostic:{version:1,stage:'module',code:'SECRET'}});assert.doesNotMatch(JSON.stringify(publicFailure(e)),/PRIVATE|SECRET/);});
test('actual controller preserves primary, exports bounded diagnosis and never-started cleanup, never full PASS',async()=>{const h=closure(),lines=[],primary=Object.assign(Error('SYNTHETIC_PRIVATE'),{code:'state_operation_failed',stateDiagnostic:{version:1,stage:'module',code:'EACCES'}});h.n.execute=async()=>{throw primary;};await assert.rejects(main({...options,output:x=>lines.push(x)},h.n),e=>e===primary);const r=lines.map(l=>JSON.parse(Buffer.from(l.split(' ')[1],'base64')));assert.equal(r[0].detail.failure.state.code,'EACCES');assert.equal(r.at(-1).detail.outcomes[0].state,'never_started');assert.equal(r.at(-1).ok,true);assert.throws(()=>parseReceipts(lines.join('\n'),options.run,SOURCE,options));const partial=parseReceipts(lines.join('\n'),options.run,SOURCE,options,{partial:true});assert.equal(partial.proof.status,'PARTIAL_FAILURE_RECEIVED');assert.doesNotMatch(lines.map(x=>Buffer.from(x.split(' ')[1],'base64').toString()).join(''),/SYNTHETIC_PRIVATE/);});
test('missing closure outcomes cannot masquerade as completion',()=>{assert.throws(()=>validateDetail({phase:'closure',ok:true,counts:[1,1,2],ids:['a'.repeat(64)],detail:{failure:null,outcomes:[]}}));});
for(const writeFails of [false,true])test('actual Native.state/Processes path preserves decoded primary before raw-write failure='+writeFails,async()=>{
 const dir=fs.mkdtempSync(path.join(os.tmpdir(),'ssb-state-process-offline-')),m={exports:{}},child=new EventEmitter();child.stdout=new EventEmitter();child.stderr=new EventEmitter();child.stdin=new EventEmitter();child.stdin.end=()=>queueMicrotask(()=>{child.stderr.emit('data',Buffer.from('SSB_STATE_DIAGNOSTIC_V1 {"version":1,"stage":"initialize-state","code":"EACCES"}\n'));child.emit('close',1,null);});
 let spawnArgs;
 vm.runInNewContext(fs.readFileSync(path.join(__dirname,'common.cjs'),'utf8'),{module:m,exports:m.exports,require:id=>id==='node:child_process'?{spawn:(...args)=>{spawnArgs=args;return child;}}:require(id),process,performance,Buffer,setTimeout,clearTimeout,AggregateError});
 const n=new Native(options);n.proc=new m.exports.Processes({deadline:performance.now()+40000,privateRoot:writeFails?path.join(dir,'missing'):dir});n.synthetic={owner:'SYNTHETIC_PRIVATE'};n.toolsRoot='/synthetic-tools';n.resources=()=>{};
 await assert.rejects(n.state('initialize',{root:'/synthetic-state',service:'synthetic',generation:'seed'}),error=>{const primary=writeFails?error.errors[0]:error;assert.equal(primary.code,'command_failed');assert.equal(primary.process.code,1);assert.equal(primary.process.closed,true);assert.equal(primary.stateDiagnostic.code,'EACCES');assert.match(primary.stack,/command_failed/);if(writeFails)assert.equal(error.errors[1].code,'evidence_write_failed');const d=publicFailure(error);validateFailure(d);assert.doesNotMatch(JSON.stringify(d),/SYNTHETIC_PRIVATE|synthetic-tools/);return true;});
 assert.equal(spawnArgs[0],process.execPath);assert.deepEqual(spawnArgs[1],require('./state-launch.cjs').stateArgs(path.join(__dirname,'state-agent.cjs')));assert.equal(spawnArgs[2].uid,1000);assert.equal(spawnArgs[2].gid,1000);n.proc.assertClosed();
});
test('large and cyclic private cause trees remain bounded and schema-valid',()=>{let e=Error('PRIVATE');e.cause=e;assert.doesNotThrow(()=>validateFailure(publicFailure(e)));for(let i=0;i<8;i++)e=new AggregateError([e,e,e,e],'PRIVATE');const d=publicFailure(e);assert.doesNotThrow(()=>validateFailure(d));assert.doesNotMatch(JSON.stringify(d),/PRIVATE/);assert.match(JSON.stringify(d),/truncated/);});
test('partial receipt refuses graceful claim without corresponding successful shutdown',()=>{const w=new Receipts(options.run,SOURCE,options,()=>{});w.emit('preflight',false);assert.throws(()=>w.emit('closure',true,{counts:[1,1,1],ids:['a'.repeat(64)],detail:{failure:null,outcomes:[{id:'a'.repeat(64),role:'api',generation:'release',state:'graceful',exit:0,code:'none'}]}}),/graceful_shutdown_receipt_missing/);});
test('import of actual helper never initializes or registers stdin execution',async()=>{const h=await helper({importsOnly:true});assert.deepEqual(fs.readdirSync(h.root),[]);assert.equal(h.stdout+h.stderr,'');});
for(const [name,config,stage]of [['wrong state owner',{stateOwner:0},'initialize-state'],['state not writable',{stateMode:0o500},'initialize-state'],['ancestor not traversable',{ancestorMode:0o700},'module'],['tools not readable',{toolsMode:0o700},'module']])test('modeled UID1000 DAC fails closed through actual stdin helper: '+name,async()=>{const h=await helper(config);assert.equal(h.proc.exitCode,1);assert.deepEqual(decodeState(h.stderr),{version:1,stage,code:'EACCES'});assert.equal(h.stdout,'');});
